"preserve_hierarchy": true
files:
  - source: /docs/es/modules/ROOT/pages/*.pot
    translation: docs/es/modules/ROOT/pages/%file_name%.%two_letters_code%.po
  - source: /docs/zh/modules/ROOT/pages/*.pot
    translation: docs/zh/modules/ROOT/pages/%file_name%.%two_letters_code%.po