= Manual de usuario de la herramienta de publicación integrada de GBIF (IPT)

_Para información sobre la última versión, incluyendo descargas, vea la página xref:releases.adoc[Releases]._

El kit de herramientas de publicación integradas de GBIF (IPT) es una aplicación web de código abierto disponible libremente que facilita el intercambio de cuatro tipos de información relacionada con la biodiversidad:

. datos primarios de ocurrencia de taxón
. listas de verificación de taxones
. muestreo de datos del evento
. metadatos generales sobre fuentes de datos.

Una instancia IPT, así como los datos y metadatos registrados a través del IPT están conectados al Registro GBIF, son indexadas para su consulta a través de la red GBIF y el portal, y son accesibles para uso público. El IPT también se puede configurar con una cuenta de DataCite para asignar DOI a los conjuntos de datos que lo transforman en un repositorio de datos.

Fundado y financiado por los gobiernos en 2001, El Global Biodiversity Information Facility (GBIF) es la mayor iniciativa multilateral del mundo para permitir el libre acceso a los datos de biodiversidad a través de Internet. https://www.gbif.org/participation/participant-list[los diversos participantes de GBIF] incluyen principalmente países y organizaciones internacionales. GBIF también tiene asociaciones formales con organismos internacionales relevantes de tratados. La misión de GBFI es promover y permitir el acceso libre y abierto a los datos de biodiversidad en todo el mundo a través de Internet para apuntalar la ciencia, la conservación y el desarrollo sostenible. Puede encontrar más información sobre GBIF en https://www.gbif.org/[GBIF.org].

Varios factores han motivado a GBIF a liderar el desarrollo del IPT:

* limitaciones de herramientas editoriales anteriores (DiGIR, TAPIR, BioCASe) para publicar y transferir fácilmente grandes conjuntos de datos;
* la necesidad de reducir la carga tanto en el servidor del editor, como en el servidor de GBIF, durante la indexación. La razón es que la indexación de DiGIR, TAPIR o BioCASe causó cargas pesadas debido a la repetición de la solicitud de respuesta HTTP.
* la necesidad de acelerar el proceso de indexación de los conjuntos de datos de ocurrencia de biodiversidad;
* la necesidad de ofrecer beneficios y servicios adicionales a los editores de datos para fomentar la publicación de datos;
* la falta de herramientas adecuadas para publicar ciertos tipos de datos sobre biodiversidad, como listas de verificación de nombres y metadatos de conjunto de datos.

Para entender cómo funciona la IPT, pruebe a ver esta concisa demostración en vivo de 25 minutos mostrando cómo un conjunto de datos se publica correctamente y se registra a través de GBIF.org.

[.responsive-video]
.Cómo publicar datos de biodiversidad a través de GBIF.org usando la IPT
video::eDH9IoTrMVE[youtube, width=100%]

== Usuarios

Si sólo está interesado en probar la IPT, por favor solicite una cuenta en https://ipt.gbif.org/[Demo IPT] enviando un correo electrónico a helpdesk@gbif.org.

La forma más sencilla de comenzar a usar IPT es solicitar una cuenta gratuita en los centros de alojamiento de datos xref:datos. doc[centro de alojamiento de datos de confianza] que te permite administrar tus propios conjuntos de datos y publicarlos a través de GBIF. rg sin el problema de configurar y mantener la IPT en su propio servidor.

De lo contrario, si desea configurar su propia instancia de IPT el punto de entrada xref:getting-started.adoc[Obteniendo Guía de Inicio].

NOTE: Asegúrese de registrarse en https://lists.gbif.org/mailman/listinfo/ipt/[IPT Mailing List], que sirve como un grupo de soporte para usuarios IPT. Es esencial que el IPT se mantenga al día para ser lo más seguro y sólido posible así que si usted es responsable de administrar un IPT, entonces debe estar registrado para ser notificado de nuevas versiones para que pueda actualizar inmediatamente.

== Desarrolladores

El desarrollo básico de la IPT está dirigido por GBIF, pero la codificación es un esfuerzo comunitario y todos son bienvenidos a unirse. Empieza navegando por https://github.com/gbif/ipt/issues[Open Issues] para encontrar algo en lo que te gustaría empezar a trabajar. Tenga en cuenta que las contribuciones son bienvenidas en forma de https://help.github.com/articles/creating-a-pull-request/[pull request] usando una rama o bifurcación del repositorio. Las instrucciones completas dirigidas a los desarrolladores pueden encontrarse en xref:developer-guide.adoc[here].

== Traductores

La interfaz de usuario de IPT y el manual necesitan internacionalización, pero es un esfuerzo de la comunidad y todos son bienvenidos a unirse. Las instrucciones completas dirigidas a los traductores pueden encontrarse en xref:translations.adoc[here].

Gracias a un enorme esfuerzo comunitario, y aprovechando el poder del https://crowdin. om/project/gbif-ipt[Crowdin] herramienta de localización, la interfaz de usuario ya ha sido traducida a siete idiomas diferentes: inglés, Francés, español, chino tradicional, brasileño, japonés y ruso.

== Agradecimientos

Un gran número de voluntarios dedicados contribuyen al éxito de este software. Con su ayuda, la IPT se ha convertido en una herramienta exitosa en uso en todo el mundo.

https://crowdin.com/[Crowdin] apoya amablemente este proyecto de código abierto dando a GBIF un acceso gratuito a su plataforma de administración de localización. Crowdin permite gestionar un gran número de traducciones simultáneas.
