= Cómo utilizar este manual

Este manual tiene tres componentes principales: una introducción con información de fondo, una serie de tutoriales paso a paso y una guía de referencia completa que incluye una sección de "comenzar" y secciones que describen en detalle los diferentes elementos de la herramienta.

prueba

Se recomienda a todos los usuarios que revisen esta parte introductoria y luego se refieran a las diferentes secciones específicas dependiendo de su(s) rol(es) con respecto a la instalación de IPT. El IPT (y este manual) diferencia tres tipos de usuarios:

* *Administradores*: a cargo de instalar y configurar la IPT. Pueden hacer cambios en todos los aspectos de una instancia de la IPT. Los administradores deben referirse a las secciones xref:getting-started.adoc[Iniciando] y xref:administration.adoc[Menú de Administración] de la guía de referencia.
* *Administradores de recursos*: son capaces de crear, editar, eliminar y administrar recursos (conjuntos de datos y metadatos). Dependiendo de la configuración que puedan o no tener derechos de registro para publicar recursos a través de la Red GBIF. Los gestores de recursos deben referirse a los diferentes xref: cómo publicar. doc[tutorials] dependiendo del tipo de datos que necesiten para tratar con (xref:resource-metadata.adoc[metadata], xref:occurrence-data. doc[occurrences], tipos de datos especiales a través de extensiones, etc. La sección xref:manage-resources.adoc[Manage Resources Menu] también será muy útil para los administradores de recursos.
* *Usuarios básicos*: Sólo pueden navegar por los recursos publicados en una instalación IPT. Para los usuarios básicos, el IPT funciona como una aplicación web simple, por lo que no se incluye ninguna explicación adicional en este manual.
